package phoneconn

import (
	"context"
	"encoding/binary"
	"encoding/json"
	"io"
	"sync"

	"github.com/danielealbano/android-remote-control-mcp-tunneld/internal/wire"
)

func decodeRenewSubmit(payload []byte) (wire.RenewSubmitPayload, error) {
	var s wire.RenewSubmitPayload
	err := json.Unmarshal(payload, &s)
	return s, err
}

// httpDataStream splices one dial-back data stream: Read pulls phone→client bytes from the /data
// request body; Write pushes client→phone bytes to the /data response body (flushed). Close signals the
// handler to return.
type httpDataStream struct {
	r     io.Reader
	w     io.Writer
	flush func()
	done  chan struct{}
	once  sync.Once
}

func (d *httpDataStream) Read(p []byte) (int, error) { return d.r.Read(p) }

func (d *httpDataStream) Write(p []byte) (int, error) {
	n, err := d.w.Write(p)
	if d.flush != nil {
		d.flush()
	}
	return n, err
}

func (d *httpDataStream) Close() error {
	d.once.Do(func() { close(d.done) })
	return nil
}

// readControlFrame reads one length-framed v2 control frame from r: [type:1][len:4 BE][payload].
func readControlFrame(r io.Reader) ([]byte, error) {
	var hdr [5]byte
	if _, err := io.ReadFull(r, hdr[:]); err != nil {
		return nil, err
	}
	n := binary.BigEndian.Uint32(hdr[1:5])
	if n > 1<<20 {
		return nil, io.ErrUnexpectedEOF
	}
	frame := make([]byte, 5+int(n))
	copy(frame, hdr[:])
	if _, err := io.ReadFull(r, frame[5:]); err != nil {
		return nil, err
	}
	return frame, nil
}

// sendRenewChallenge issues a fresh challenge to the phone. The nonce is minted by the renew callback's
// closure over the enroll service; here we just relay a RENEW_CHALLENGE the OnRenew flow will validate.
func (h *Handler) sendRenewChallenge(ctx context.Context, c *conn) {
	// The renewal challenge is generated by the enroll service on RENEW_SUBMIT; to keep the exchange
	// simple, the server echoes a per-connection challenge marker that the phone includes in its
	// attestation. server.Run wires OnRenew to the enroll service's renewal path.
	if h.onRenew == nil {
		return
	}
	frame, _ := wire.EncodeControl(wire.CtrlRenewChallenge, wire.RenewChallengePayload{Nonce: c.connID})
	select {
	case c.send <- frame:
	case <-ctx.Done():
	}
}

// handleRenewSubmit runs the renewal via OnRenew and pushes the result (or an ERROR) to the phone. The
// connection stays up on the OLD certs on failure.
func (h *Handler) handleRenewSubmit(ctx context.Context, c *conn, payload []byte) {
	if h.onRenew == nil {
		return
	}
	sub, err := decodeRenewSubmit(payload)
	if err != nil {
		return
	}
	push, err := h.onRenew(ctx, c.name, sub)
	if err != nil {
		ef, _ := wire.EncodeControl(wire.CtrlError, wire.ErrorPayload{Reason: "renew_failed", Retryable: true})
		select {
		case c.send <- ef:
		case <-ctx.Done():
		}
		return
	}
	pf, _ := wire.EncodeControl(wire.CtrlCertPush, push)
	select {
	case c.send <- pf:
	case <-ctx.Done():
	}
}
